In [2]:
import numpy as np

1. Решите линейную систему:

In [3]:
A = np.array([[1, 2, 3],
            [4, 0, 6],
            [7, 8, 9]])
B = np.array([12, 2, 1])

In [4]:
X = np.linalg.solve(A, B)
X

array([-9.2       ,  0.9       ,  6.46666667])

2. Найдите псевдорешение:

In [5]:
A = np.array([[1, 2, -1],
             [3, -4, 0],
             [8, -5, 2],
             [2, 0, -5],
             [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])

In [6]:
X = np.linalg.lstsq(A, B)
X

C:\Users\rikks\AppData\Local\Temp\ipykernel_10496\2775675865.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  X = np.linalg.lstsq(A, B)


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

3. Сколько решений имеет линейная система:

In [7]:
A = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
B = np.array([[12, 2, 1]])

Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее. 

In [8]:
C = np.concatenate((A, B.T), axis=1)
C

array([[ 1,  2,  3, 12],
       [ 4,  5,  6,  2],
       [ 7,  8,  9,  1]])

In [9]:
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

(2, 3)

Система не имеет решений, поскольку ранг основной матрицы меньше ранга расширенной матрицы.

In [18]:
# Изменим В, чтобы были решения
B = np.array([56, 2, 1])

In [20]:
X = np.linalg.solve(A, B)
X

(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

4. Вычислите LU-разложение матрицы:

In [ ]:
A = np.array([[1, 2, 3],
             [2, 16, 21],
             [4, 28, 73]])

In [ ]:
import scipy
import scipy.linalg

In [ ]:
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.

5. Найдите нормальное псевдорешение недоопределенной системы:  
Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум. 

In [ ]:
A = np.array([[1, 2, -1],
             [8, -5, 2]])
B = np.array([1, 12])

In [ ]:
import matplotlib.pyplot as plt

def Q(x, y, z):
    return x**2 + y**2 + z**2

x = np.linspace(-1, 10, 200)


In [ ]:
np.linalg.lstsq(A, B)

(array([ 1.38191882, -0.18081181,  0.0202952 ]),
 array([], dtype=float64),
 2,
 array([9.65316119, 2.41173777]))

6. Найдите одно из псевдорешений вырожденной системы:  
Попробуйте также отыскать и нормальное псевдорешение.

In [ ]:
A = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
B = np.array([2, 5, 11])

In [ ]:
np.linalg.lstsq(A, B)

(array([ 1.25,  0.5 , -0.25]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]))