In [1]:
import numpy as np

Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.

In [2]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [3]:
# Умножение на число
b = a * 2
b

array([2, 4, 6, 8])

In [4]:
# Сложение каждого элемента матрицы с числом
c = a + 3
c

array([4, 5, 6, 7])

In [5]:
# Сложение двух матриц
d = np.add(a, b)
d

array([ 3,  6,  9, 12])

In [6]:
# Вычитание матриц
d1 = np.subtract(b, a)
d1

array([1, 2, 3, 4])

In [7]:
# Транспонирование матрицы
f = d.T
f

array([ 3,  6,  9, 12])

In [8]:
# Умножение матриц
g = np.dot(d, f)
g

270

Вычислите, по возможности не используя программирование: (5Е)–1, где Е – единичная матрица размера 5х5.

In [9]:
e = np.identity(5)
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Обратная матрица единичной является такая же единичная - по определению обратной матрицы.

Вычислите определитель:
[[1, 2, 3], [4, 0, 6], [7, 8, 9]]

In [10]:
a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [11]:
np.linalg.det(a)

59.999999999999986

Вычислите матрицу, обратную данной a

In [12]:
a_inv = np.linalg.inv(a)
a_inv

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

Приведите пример матрицы 4х4, ранг которой равен 1.

Не знаю

Вычислите скалярное произведение двух векторов:  
(1, 5)  и  (2, 8)

In [13]:
a = np.array([1, 5])
b = np.array([2, 8])
np.inner(a, b)

42

Вычислите смешанное произведение трех векторов:
(1, 5, 0), (2, 8, 7) и (7, 1.5, 3)

In [14]:
a = np.array([1, 5, 0])
b = np.array([2, 8, 7])
c = np.array([7, 1.5, 3])

In [15]:
v = np.cross(a, b)
v

array([35, -7, -2])

In [16]:
np.inner(v, c)

228.5